In [ ]:
import csv
import random
import time
import psycopg2

# Connect to the Postgres database
conn = psycopg2.connect(
    host="localhost",
    port="5432",
    user="root",
    password="secret",
    database="root"
)

cur = conn.cursor()

# read CSV file
with open('food_coded.csv', 'r') as f:
    reader = csv.reader(f)
    # get the header row and create the table
    header = next(reader)
    table_name = 'food'
    create_table_query = f"CREATE TABLE IF NOT EXISTS {table_name} (food_id SERIAL PRIMARY KEY,{','.join([f'{col} VARCHAR(355)' for col in header])})"
    cur.execute(create_table_query)
    conn.commit()

    # insert data into the table row-by-row
    for row in reader:
        insert_query = f"INSERT INTO {table_name} (GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,cook,comfort_food_reasons_coded_1,cuisine,diet_current,diet_current_coded,drink,eating_changes,eating_changes_coded,eating_changes_coded1,eating_out,employment,ethnic_food,exercise,father_education,father_profession,fav_cuisine,fav_cuisine_coded,fav_food,food_childhood,fries,fruit_day,grade_level,greek_food,healthy_feeling,healthy_meal,ideal_diet,ideal_diet_coded,income,indian_food,italian_food,life_rewarding,marital_status,meals_dinner_friend,mother_education,mother_profession,nutritional_check,on_off_campus,parents_cook,pay_meal_out,persian_food,self_perception_weight,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight) VALUES ({','.join(['%s']*len(header))})"
        cur.execute(insert_query, row)
        conn.commit()
        # simulate writing duration between 0 < d < 2 seconds
        duration = random.uniform(0, 2)
        #time.sleep(1)
        print(f"Inserting row: {row}")
        #print(create_table_query)
# close the cursor and connection
cur.close()
conn.close()

In [ ]:
import csv
import random
import time
import psycopg2

# Connect to the Postgres database
conn = psycopg2.connect(
    host="localhost",
    port="5432",
    user="root",
    password="secret",
    database="root"
)

cur = conn.cursor()

# read CSV file
with open('food_coded.csv', 'r') as f:
    reader = csv.reader(f)
    # get the header row and create the table
    header = next(reader)
    table_name = 'food'
    create_table_query = f"CREATE TABLE IF NOT EXISTS {table_name} (food_id SERIAL PRIMARY KEY,gpa VARCHAR,\
    Gender int,\
    breakfast int,\
    calories_chicken int,\
    calories_day float,\
    calories_scone float,\
    coffee int,\
    comfort_food varchar,\
    comfort_food_reasons varchar,\
    comfort_food_reasons_coded float DEFAULT NULL,\
    cook float,\
    comfort_food_reasons_coded_1 int,\
    cuisine float,\
    diet_current varchar,\
    diet_current_coded int,\
    drink float,\
    eating_changes varchar,\
    eating_changes_coded int,\
    eating_changes_coded1 int,\
    eating_out int,\
    employment float,\
    ethnic_food int,\
    exercise float,\
    father_education float,\
    father_profession varchar,\
    fav_cuisine varchar,\
    fav_cuisine_coded int,\
    fav_food float,\
    food_childhood varchar,\
    fries int,\
    fruit_day int,\
    grade_level int,\
    greek_food int,\
    healthy_feeling int,\
    healthy_meal varchar,\
    ideal_diet varchar,\
    ideal_diet_coded int,\
    income float,\
    indian_food int,\
    italian_food int,\
    life_rewarding float,\
    marital_status float,\
    meals_dinner_friend varchar,\
    mother_education float,\
    mother_profession varchar,\
    nutritional_check int,\
    on_off_campus float,\
    parents_cook int,\
    pay_meal_out int,\
    persian_food float,\
    self_perception_weight float,\
    soup float,\
    sports float,\
    thai_food int,\
    tortilla_calories float,\
    turkey_calories int,\
    type_sports varchar,\
    veggies_day int,\
    vitamins int,\
    waffle_calories int,weight varchar);"
    cur.execute(create_table_query)
    conn.commit()
    print('create table successful.')

In [ ]:
# insert data into the table row-by-row
conn = psycopg2.connect(
    host="localhost",
    port="5432",
    user="root",
    password="secret",
    database="root"
)

cur = conn.cursor()

# read CSV file
with open('food_coded.csv', 'r') as f:
    reader = csv.reader(f)
    # get the header row and create the table
    header = next(reader)
    table_name = 'food'
    for row in reader:
        insert_query = f"INSERT INTO {table_name} (GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,cook,comfort_food_reasons_coded_1,cuisine,diet_current,diet_current_coded,drink,eating_changes,eating_changes_coded,eating_changes_coded1,eating_out,employment,ethnic_food,exercise,father_education,father_profession,fav_cuisine,fav_cuisine_coded,fav_food,food_childhood,fries,fruit_day,grade_level,greek_food,healthy_feeling,healthy_meal,ideal_diet,ideal_diet_coded,income,indian_food,italian_food,life_rewarding,marital_status,meals_dinner_friend,mother_education,mother_profession,nutritional_check,on_off_campus,parents_cook,pay_meal_out,persian_food,self_perception_weight,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight) VALUES ({','.join(['%s']*len(header))})"
        row = [None if value == "" else value for value in row]
        cur.execute(insert_query, row)
        conn.commit()
        # simulate writing duration between 0 < d < 2 seconds
        duration = random.uniform(0, 2)
        time.sleep(1)
        print(f"Inserting row: {row}")

# close the cursor and connection
cur.close()
conn.close()

In [ ]:
#docker-compose exec elasticsearch curl -XGET "localhost:9200/food/_search?format=json&pretty"
#docker exec -it kafka kafka-topics --list --bootstrap-server localhost:9092

#docker-compose exec ksqldb-cli  ksql http://ksqldb-server:8088
#RUN SCRIPT '/etc/sql/all.sql';
#RUN SCRIPT '/etc/sql/create_stream1.sql';

In [ ]:
#1.read selected data from topic1
#CREATE STREAM stream1 WITH (KAFKA_TOPIC='food', VALUE_FORMAT='AVRO');
#2.send selected data to topic2 
#CREATE STREAM stream2 WITH (KAFKA_TOPIC='topic2', VALUE_FORMAT='AVRO') AS SELECT gpa FROM stream1;

CREATE STREAM stream2 WITH (KAFKA_TOPIC='topic3_1', VALUE_FORMAT='AVRO') AS SELECT CAST(gpa AS double) AS gpa FROM stream1;
EMIT CHANGES;

In [ ]:
##question1
#CREATE STREAM stream1 WITH (KAFKA_TOPIC='topic1_food', VALUE_FORMAT='AVRO');

CREATE STREAM stream2 WITH (KAFKA_TOPIC='topic2', VALUE_FORMAT='AVRO') AS SELECT gender as GENDER, AVG(CAST(GPA AS DOUBLE)) AS AVG_GPA
FROM stream1
GROUP BY gender;


CREATE TABLE stream2 WITH (KAFKA_TOPIC='topic3_1', VALUE_FORMAT='AVRO') AS 
    SELECT AVG(calories_chicken) AS AVG_cal , GENDER as GENDER
    FROM stream1 
    GROUP BY gender;

In [ ]:
CREATE STREAM stream1 WITH (
    KAFKA_TOPIC='topic1_food',
    VALUE_FORMAT='AVRO'
);
CREATE table stream1 WITH (
    KAFKA_TOPIC='topic1_food',
    VALUE_FORMAT='AVRO'
);

create stream stream2  with( KAFKA_TOPIC='topic3_1',value_format='AVRO') as 
select gender,AVG(CAST(GPA AS DOUBLE)) AS AVG_GPA  from stream1 group by gender emit changes; 


CREATE STREAM stream1 (gpa VARCHAR, gender VARCHAR) 
    WITH (KAFKA_TOPIC='topic1_food', VALUE_FORMAT='AVRO');

CREATE STREAM stream2 WITH (VALUE_FORMAT='AVRO') AS 
    SELECT CAST(gpa AS DOUBLE) AS gpa_double, gender 
    FROM stream1;

CREATE TABLE stream3 WITH (KAFKA_TOPIC='topic3_1', VALUE_FORMAT='AVRO') AS 
    SELECT gender, AVG(gpa_double) AS avg_gpa 
    FROM stream1
    GROUP BY gender;

In [ ]:
create table stream3 with( KAFKA_TOPIC='topic3_1',value_format='AVRO') as SELECT gender as sex ,avg(calories_chicken) as avg_cal
FROM stream1
GROUP BY gender
EMIT CHANGES;